### ISSUE TITLE
Storage controller and AE2 Storage bus

### ISSUE THREAD

**Issue by EugeneLagonski** [Salandora/SophisticatedStorage#10]
**Describe the bug**
Storage controller crashes AE2 storage bus when trying to get items from sophisticated chests system

**To Reproduce**
1. Place a chest and a storage controller
2. Connect AE2 storage bus to Sophisticated storage controller
3. ME Crafting Terminal
4. See items in the Sophisticated system
5. Trying to get items
6. ME Crafting terminal stops showing the storage controller content
7. An error in logs appears

**Expected behavior**
Getting items from the storage controller using AE2 ME Crafting Terminal successfully.

AE2 storage bus works correctly with Sophisticated chests, bank docks and vanilla chests

**Screenshots**
Setup screenshot
(AE2 energy acceptor, AE2 Storage bus, AE2 Crafting terminal, Sophisticated storage controller and diamond chest)
![setup](https://github.com/Salandora/SophisticatedStorage/assets/22728161/72bbdb7f-d69e-40f6-a9b7-394ec05f651a)

Terminal content before trying to get items
![2024-06-16_01 11 40](https://github.com/Salandora/SophisticatedStorage/assets/22728161/b3fb8278-565b-4809-8ebf-f6871f2195ab)

Terminal content after trying to get items
![2024-06-16_01 11 47](https://github.com/Salandora/SophisticatedStorage/assets/22728161/cec164ee-38b8-4af7-ae3d-fa3dd31d613c)

<details><summary>Error in logs</summary>
<p>
[01:11:45] [Server thread/ERROR]: Error executing task on Server
org.apache.commons.lang3.NotImplementedException: null
	at net.p3pp3rf1y.sophisticatedcore.controller.ControllerBlockEntityBase.extract(ControllerBlockEntityBase.java:739) ~[sophisticatedcore-0.5.109+mc1.20.1-SNAPSHOT-build.76.jar:?]
	at net.p3pp3rf1y.sophisticatedcore.controller.ControllerBlockEntityBase.extract(ControllerBlockEntityBase.java:50) ~[sophisticatedcore-0.5.109+mc1.20.1-SNAPSHOT-build.76.jar:?]
	at net.p3pp3rf1y.sophisticatedcore.inventory.CachedFailedInsertInventoryHandler.extract(CachedFailedInsertInventoryHandler.java:104) ~[sophisticatedcore-0.5.109+mc1.20.1-SNAPSHOT-build.76.jar:?]
	at net.p3pp3rf1y.sophisticatedcore.inventory.CachedFailedInsertInventoryHandler.extract(CachedFailedInsertInventoryHandler.java:16) ~[sophisticatedcore-0.5.109+mc1.20.1-SNAPSHOT-build.76.jar:?]
	at appeng.me.storage.StorageAdapter.extract(StorageAdapter.java:90) ~[appliedenergistics2-fabric-15.2.0.jar:?]
	at appeng.me.storage.CompositeStorage.extract(CompositeStorage.java:57) ~[appliedenergistics2-fabric-15.2.0.jar:?]
	at appeng.me.storage.DelegatingMEInventory.extract(DelegatingMEInventory.java:46) ~[appliedenergistics2-fabric-15.2.0.jar:?]
	at appeng.me.storage.MEInventoryHandler.extract(MEInventoryHandler.java:95) ~[appliedenergistics2-fabric-15.2.0.jar:?]
	at appeng.me.storage.NetworkStorage.extract(NetworkStorage.java:225) ~[appliedenergistics2-fabric-15.2.0.jar:?]
	at appeng.api.storage.StorageHelper.poweredExtraction(StorageHelper.java:92) ~[appliedenergistics2-fabric-15.2.0.jar:?]
	at appeng.api.storage.StorageHelper.poweredExtraction(StorageHelper.java:71) ~[appliedenergistics2-fabric-15.2.0.jar:?]
	at appeng.menu.me.common.MEStorageMenu.moveOneStackToPlayer(MEStorageMenu.java:654) ~[appliedenergistics2-fabric-15.2.0.jar:?]
	at appeng.menu.me.common.MEStorageMenu.handleNetworkInteraction(MEStorageMenu.java:470) ~[appliedenergistics2-fabric-15.2.0.jar:?]
	at appeng.menu.me.common.MEStorageMenu.handleInteraction(MEStorageMenu.java:419) ~[appliedenergistics2-fabric-15.2.0.jar:?]
	at appeng.core.sync.packets.MEInteractionPacket.serverPacketData(MEInteractionPacket.java:66) ~[appliedenergistics2-fabric-15.2.0.jar:?]
	at appeng.core.sync.network.ServerNetworkHandler.lambda$handlePacketFromClient$3(ServerNetworkHandler.java:82) ~[appliedenergistics2-fabric-15.2.0.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
</p>
</details> 

**Versions**
Minecraft version 1.20.1
Modpack All of Fabric: 2.2.3
Sophisticated Core: 0.5.109
Sophisticated Storage: 0.8.60
Applied Energistics 2: 15.2.0

**Comment by Salandora** [comment]
This should be fixed in dev. (Related to another bug with the same error) 
I prepare the bugfix release today.

**Comment by Salandora** [comment]
Bugfix release is out.
If you still get crashes please open a new issue, also please put logs into code blocks, mclo.gs, pastebin or gist.
It's really hard to read like this.

**Comment by EugeneLagonski** [comment]
Thank you! It works!
