### ISSUE TITLE
Crashes on launch with Sodium when using Quilt

### ISSUE THREAD

**Issue by dombomb64** [Salandora/SophisticatedStorage#18]
**Describe the bug**
If Quilt is chosen as the mod loader and Sodium, Indium, and the required dependencies are used, Sophisticated Storage will crash the game. Sophisticated Backpacks does not have this issue.

Crash Log:

```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-06-26 15:16:32
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'sophisticatedstorage'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:55)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:557)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NullPointerException: other
	at java.base/java.util.Objects.requireNonNull(Objects.java:235)
	at org.quiltmc.loader.impl.metadata.qmj.SemanticVersionImpl.compareTo(SemanticVersionImpl.java:167)
	at org.quiltmc.loader.impl.fabric.util.version.Quilt2FabricVersion.compareTo(Quilt2FabricVersion.java:59)
	at net.fabricmc.loader.util.version.SemanticVersionImpl.compareTo(SemanticVersionImpl.java:120)
	at net.fabricmc.loader.util.version.SemanticVersionImpl.compareTo(SemanticVersionImpl.java:32)
	at net.fabricmc.loader.api.metadata.version.VersionComparisonOperator$1.test(VersionComparisonOperator.java:31)
	at net.fabricmc.loader.api.metadata.version.VersionComparisonOperator.test(VersionComparisonOperator.java:158)
	at net.fabricmc.loader.impl.util.version.VersionPredicateParser$SingleVersionPredicate.test(VersionPredicateParser.java:158)
	at net.fabricmc.loader.impl.util.version.VersionPredicateParser$MultiVersionPredicate.test(VersionPredicateParser.java:222)
	at net.fabricmc.loader.impl.util.version.VersionPredicateParser$MultiVersionPredicate.test(VersionPredicateParser.java:210)
	at net.p3pp3rf1y.sophisticatedstorage.init.ModCompat$CompatInfo.lambda$isLoaded$0(ModCompat.java:71)
	at java.base/java.util.Optional.map(Optional.java:260)
	at net.p3pp3rf1y.sophisticatedstorage.init.ModCompat$CompatInfo.isLoaded(ModCompat.java:71)
	at net.p3pp3rf1y.sophisticatedstorage.init.ModCompat.initCompats(ModCompat.java:55)
	at net.p3pp3rf1y.sophisticatedstorage.SophisticatedStorage.onInitialize(SophisticatedStorage.java:40)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:55)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62)
	... 15 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:55)
	at net.minecraft.class_310.<init>(class_310.java:458)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:557)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.1.52-valve16-1-neptune-61
	Java Version: 17.0.11, Flathub
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Flathub
	Memory: 288858112 bytes (275 MiB) / 637534208 bytes (608 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Custom APU 0932
	Identifier: AuthenticAMD Family 23 Model 145 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Device
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x1435
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 8431.19
	Virtual memory used (MB): 4513.68
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Fabric Mods: 
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		indium: Indium 1.0.32+mc1.20.1
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.1
		quilt_loader: Quilt Loader 0.26.0
		sodium: Sodium 0.5.10+mc1.20.1
		sophisticatedcore: Sophisticated Core 0.5.109+mc1.20.1-SNAPSHOT-build.104
		sophisticatedstorage: Sophisticated Storage 0.8.60+mc1.20.1-SNAPSHOT-build.104
			forgeconfigapiport: Forge Config API Port 8.0.0
			mixinextras: MixinExtras 0.3.5
			porting_lib_extensions: Porting Lib Extensions 2.3.0+1.20.1
				porting_lib_accessors: Porting Lib Accessors 2.3.0+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.0+1.20.1
				porting_lib_common: Porting Lib Common 2.3.0+1.20.1
				reach-entity-attributes: Reach Entity Attributes 2.4.0
			porting_lib_loot: Porting Lib Loot 2.3.0+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.0+1.20.1
			porting_lib_model_loader: Porting Lib Model Loader 2.3.0+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.0+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.0+1.20.1
				porting_lib_core: Porting Lib Core 2.3.0+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.0+1.20.1
			team_reborn_energy: Energy 3.0.0
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'quilt'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

No other mods were being used besides the ones mentioned.

**To Reproduce**
1. Use Quilt to run the game with this mod, Sophisticated Core, Sodium, Indium, and Quilted Fabric API. 
2. The game crashes before the window opens.

**Expected behavior**
The game boots as it would with Fabric.
 
**Versions**
Minecraft: 1.20.1
Quilt: 0.26.0
Quilted Fabric API: 0.92.2
Sodium: 0.5.10
Indium: 1.0.32
Sophisticated Storage: 0.5.109
Sophisticated Core: 0.8.60

**Comment by Salandora** [comment]
Yes unfortunately this seems to be a bug in quilt's fabric VersionPredicate class.
I'm working on a workaround for this.

**Comment by Salandora** [comment]
Okay kind of a bug in quilt but also me using the implementation instead of the api.
So fixed in dev.

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
