### ISSUE TITLE
Serverside Only - I/O Block respawns and fills chat with error when looking at it's ghost

### ISSUE THREAD

**Issue by Ruaridh-Smith** [Salandora/SophisticatedStorage#35]
**Describe the bug**
Just started getting setup on my server with storage system and placed some I/O Blocks that I now can't destroy without them coming back and fills up the terminal with errors every tick. It mentions jade which I might guess is what's causing the log error since i'm looking at a block that doesn't exist anymore but not sure about why the block is ghosting. It isn't a lag issue as the server is hosted locally and performance is stellar otherwise and no other block does this so far. I have tried restarting/reloading several times both when the blocks are visible and after breaking but not letting them reappear and regardless of what I do they are still there on restart.
If this is an error on my end forgive me for wrongful report but I would appreciate any help!

It is a fairly large modpack we have put together so it is hard to guess if a specific mod could be conflicting.

**To Reproduce**
1. Only on server, the bug seems to not be on singleplayer worlds
2. Setup barrels with storage controller
3. Place I/O block
4. Server Terminal fills with error every tick
5. Break block
6. Right click/place block/ interact anywhere nearby
7. Block respawns with collision but no interactivity

**Expected behavior**
Block should behave as described and be breakable 

**Versions**
Latest ver. of all Sophisticated as of 28/10/24
MC ver. 1.20.1
Fabric ver. 0.16.7

**Error**
`[12:43:27] [Server thread/ERROR]: Error executing task on Server
java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientChunkEvents in environment type SERVER
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.7.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.p3pp3rf1y.sophisticatedstorage.block.StorageIOBlockEntity.<init>(StorageIOBlockEntity.java:35) ~[sophisticatedstorage-1.20.1-0.10.45.32.jar:?]
        at net.p3pp3rf1y.sophisticatedstorage.block.StorageIOBlockEntity.<init>(StorageIOBlockEntity.java:40) ~[sophisticatedstorage-1.20.1-0.10.45.32.jar:?]
        at net.p3pp3rf1y.sophisticatedstorage.block.StorageIOBlock.method_10123(StorageIOBlock.java:26) ~[sophisticatedstorage-1.20.1-0.10.45.32.jar:?]
        at net.minecraft.class_2818.method_12208(class_2818.java:303) ~[server-intermediary.jar:?]
        at net.minecraft.class_2818.method_12201(class_2818.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_8321(class_1937.java:559) ~[server-intermediary.jar:?]
        at snownee.jade.impl.BlockAccessorImpl.lambda$fromNetwork$1(BlockAccessorImpl.java:98) ~[Jade-1.20-Fabric-11.12.0.jar:?]
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.1-jre.jar:?]
        at snownee.jade.impl.BlockAccessorImpl.getBlockEntity(BlockAccessorImpl.java:123) ~[Jade-1.20-Fabric-11.12.0.jar:?]
        at snownee.jade.impl.BlockAccessorImpl.lambda$handleRequest$0(BlockAccessorImpl.java:63) ~[Jade-1.20-Fabric-11.12.0.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

[12:43:29] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@5a754d00, suppressing error
java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientChunkEvents in environment type SERVER
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.7.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.p3pp3rf1y.sophisticatedstorage.block.StorageIOBlockEntity.<init>(StorageIOBlockEntity.java:35) ~[sophisticatedstorage-1.20.1-0.10.45.32.jar:?]
        at net.p3pp3rf1y.sophisticatedstorage.block.StorageIOBlockEntity.<init>(StorageIOBlockEntity.java:40) ~[sophisticatedstorage-1.20.1-0.10.45.32.jar:?]
        at net.p3pp3rf1y.sophisticatedstorage.block.StorageIOBlock.method_10123(StorageIOBlock.java:26) ~[sophisticatedstorage-1.20.1-0.10.45.32.jar:?]
        at net.minecraft.class_2818.method_12208(class_2818.java:303) ~[server-intermediary.jar:?]
        at net.minecraft.class_2818.method_12201(class_2818.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_8321(class_1937.java:559) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.handler$dad000$polymer-core$polymer$updateMoreBlocks(class_3244.java:14553) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1161) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]`

**Comment by Salandora** [comment]
Thanks for reporting this, will fix it and push an update

**Comment by Salandora** [comment]
Pushed the update. Should be fixed.
