### ISSUE TITLE
[Bug] Placing a Block of Experience from the Create mod into a Limited Barrel crashes the game

### ISSUE THREAD

**Issue by jonathansharpe** [Salandora/SophisticatedStorage#9]
**Describe the bug**

Placing a Block of Experience from the Create Mod into a Limited Barrel of any kind crashes the game
```
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 2024-06-12 22:55:05
Description: Tessellating block in world - Indigo Renderer

java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.impl.client.indigo.renderer.material.RenderMaterialImpl.disableDiffuse()" because "material" is null
	at net.fabricmc.fabric.impl.client.indigo.renderer.material.RenderMaterialImpl.setDisableDiffuse(RenderMaterialImpl.java:46)
	at net.fabricmc.fabric.impl.client.indigo.renderer.mesh.MutableQuadViewImpl.fromVanilla(MutableQuadViewImpl.java:204)
	at net.p3pp3rf1y.sophisticatedstorage.client.util.QuadTransformers.process(QuadTransformers.java:34)
	at net.p3pp3rf1y.sophisticatedstorage.client.render.BarrelBakedModelBase.addRenderedItemSide(BarrelBakedModelBase.java:526)
	at net.p3pp3rf1y.sophisticatedstorage.client.render.BarrelBakedModelBase.addDisplayItemQuads(BarrelBakedModelBase.java:493)
	at net.p3pp3rf1y.sophisticatedstorage.client.render.BarrelBakedModelBase.method_4707(BarrelBakedModelBase.java:281)
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:59)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1041)
	at net.p3pp3rf1y.sophisticatedstorage.client.render.BarrelBakedModelBase.emitBlockQuads(BarrelBakedModelBase.java:197)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:98)
	at net.minecraft.class_846$class_851$class_4578.redirect$bab000$fabric-renderer-indigo$hookChunkBuildTessellate(class_846.java:783)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:579)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:490)
	at net.minecraft.class_846.method_22757(class_846.java:141)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.fabric.impl.client.indigo.renderer.material.RenderMaterialImpl.setDisableDiffuse(RenderMaterialImpl.java:46)
	at net.fabricmc.fabric.impl.client.indigo.renderer.mesh.MutableQuadViewImpl.fromVanilla(MutableQuadViewImpl.java:204)
	at net.p3pp3rf1y.sophisticatedstorage.client.util.QuadTransformers.process(QuadTransformers.java:34)
	at net.p3pp3rf1y.sophisticatedstorage.client.render.BarrelBakedModelBase.addRenderedItemSide(BarrelBakedModelBase.java:526)
	at net.p3pp3rf1y.sophisticatedstorage.client.render.BarrelBakedModelBase.addDisplayItemQuads(BarrelBakedModelBase.java:493)
	at net.p3pp3rf1y.sophisticatedstorage.client.render.BarrelBakedModelBase.method_4707(BarrelBakedModelBase.java:281)
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:59)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1041)
	at net.p3pp3rf1y.sophisticatedstorage.client.render.BarrelBakedModelBase.emitBlockQuads(BarrelBakedModelBase.java:197)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:98)

-- Block being tessellated --
Details:
	Block: Block{sophisticatedstorage:limited_barrel_1}[facing=north,flat_top=false,ticking=false,vertical_facing=no]
	Block location: World: (0,-60,7), Section: (at 0,4,7 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
Stacktrace:
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:98)
	at net.minecraft.class_846$class_851$class_4578.redirect$bab000$fabric-renderer-indigo$hookChunkBuildTessellate(class_846.java:783)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:579)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:490)
	at net.minecraft.class_846.method_22757(class_846.java:141)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Affected level --
Details:
	All players: 1 total; [class_746['AvgUsrName'/123, l='ClientLevel', x=0.51, y=-60.00, z=4.93]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2497 game time, 2497 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_43589(class_310.java:895)
	at net.minecraft.class_310.method_1514(class_310.java:791)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.9.3-zen1-1-zen
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1221247096 bytes (1164 MiB) / 2147483648 bytes (2048 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: GA104 [GeForce RTX 3070 Ti]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x2482
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 16010.95
	Virtual memory used (MB): 20683.16
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms2048m -Xmx4096m
	Fabric Mods: 
		create: Create 0.5.1-f-build.1417+mc1.20.1
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-2
			forgeconfigapiport: Forge Config API Port 8.0.0
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.3.2+1.20.1
			porting_lib_base: Porting Lib Base 2.3.2+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.2+1.20.1
				porting_lib_common: Porting Lib Common 2.3.2+1.20.1
				porting_lib_config: Porting Lib Config 2.3.2+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.2+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.2+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.2+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.2+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.2+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.2+1.20.1
				porting_lib_core: Porting Lib Core 2.3.2+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.2+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.2+1.20.1
			porting_lib_models: Porting Lib Models 2.3.2+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.2+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.2+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.2+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.2+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.2+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.1
		mkb: ModernKeyBinding 1.2.0
		sophisticatedcore: Sophisticated Core 0.5.109+mc1.20.1-SNAPSHOT-build.76
			team_reborn_energy: Energy 3.0.0
		sophisticatedstorage: Sophisticated Storage 0.8.60+mc1.20.1-SNAPSHOT-build.76
			porting_lib_loot: Porting Lib Loot 2.3.0+1.20.1
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 555.52.04, NVIDIA Corporation
	Window size: 3440x1362
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	CPU: 12x AMD Ryzen 5 5600X 6-Core Processor
	Server Running: true
	Player Count: 1 / 8; [class_3222['AvgUsrName'/123, l='ServerLevel[New World]', x=0.51, y=-60.00, z=4.93]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
```

**To Reproduce**
1. Place down a Limited Barrel (of any kind)
2. Right-click the Limited Barrel with a Block of Experience
3. The "1" appears inside the Limited Barrel front face, but no block appears above
4. Game crashes

**Expected behavior**

I expected the item to go into the barrel

**Versions**
Sophisticated Storage 0.8.60+mc1.20.1-build.76

**Comment by Salandora** [comment]
Yeah it's a known bug and fixed in dev.
Will do another bugfix release soon.
Have one more thing on my list I want to test/fix before that.

**Comment by Salandora** [comment]
Bugfix release is out.
